### ISSUE TITLE
"Non json result" in scan response

### ISSUE THREAD

**Issue by muhyuddin** [danieljampen/multiav#5]
OS: Ubuntu 18.04
Followed all instructions step by step. 
Whenever trying to scan some files, all engines giving "Scan failed. Error: non json result"

![image](https://user-images.githubusercontent.com/34711191/87233589-4839e380-c3e2-11ea-8737-141c69760821.png)

**Comment by jampe** [comment]
sorry for the late reply. to be honest, I can't really help you without logs. Could you post the output of multiav and  your config?

**Comment by muhyuddin** [comment]
Updated: multiav-output file...
Sorry for the late reply. I reconfigured the system again, but still, the error is the same.
These are the files for the console output of MultiAV and configurations.

[config.txt](https://github.com/jampe/MultiAV-Extended/files/5091543/config.txt)
[multiav-output.txt](https://github.com/jampe/MultiAV-Extended/files/5092104/multiav-output.txt)

**Comment by fareedfauzi** [comment]
Happened to me also on certain samples

![image](https://user-images.githubusercontent.com/56353946/91117226-b13e9780-e6c0-11ea-92b6-adad354af19d.png)

**Comment by muhyuddin** [comment]
> Happened to me also on certain samples
> 
> ![image](https://user-images.githubusercontent.com/56353946/91117226-b13e9780-e6c0-11ea-92b6-adad354af19d.png)

Did you find any workaround? Or even some other multiav tool ?

**Comment by jampe** [comment]
Hi,

The quted non json result errors by @fareedfauzi are caused by the docker container running the scan. as you can see in the error message, the container respectively the process running it was killed when scanning the binary. The non json error then comes from multiav, as it expects the docker container to return a json response. This is a problem of the used malice docker containers, not multiav.

I'm not sure how i should fix this from the multiav side.

**Comment by muhyuddin** [comment]
Got it. Thanks.
